name: BarBeeQJobs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-26

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        with:
          submodules: true
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: 26
      - name: Install Mint
        run: brew install mint
      - name: Cache Mint modules
        id: cache-mint
        uses: actions/cache@v4.3.0
        env:
          cache-name: cache-mint-modules
        with:
          path: ~/.mint
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Mintfile') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - if: ${{ steps.cache-mint.outputs.cache-hit != 'true' }}
        name: List the state of Mint modules
        continue-on-error: true
        run: mint list
      - name: Generate Xcode project
        run: mint bootstrap && mint run xcodegen
      - name: Build and test iOS
        run: xcodebuild test -project BarBeeQ.xcodeproj -scheme BarBeeQApp -destination "platform=iOS Simulator,OS=26.0.1,name=iPhone 17" -skipMacroValidation
